[mailbox]
source = imaps://spirida%40mailbox.org@imap.mailbox.org:993
outgoing = smtps://spirida%40mailbox.org@smtp.mailbox.org:465
from = Dominik Rusovac <spirida@mailbox.org>

default = INBOX
copy-to = Sent

source-cred-cmd = pass show email/mailbox.org
outgoing-cred-cmd = pass show email/mailbox.org
